In [1]:
import numpy as np

### 1. Write a program to create a 5 dimensional array with all zeros and ones

In [16]:
np.zeros((1,1,1,5,5),dtype=int)

array([[[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]]])

In [23]:
np.ones((1,1,1,5,5),dtype=int)

array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])

### 2. Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [34]:
a1=np.array([np.zeros(10),np.ones(10),np.full(10,5)])
a1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [32]:
a1.shape

(3, 10)

### 3. Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [40]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 4.  Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9

In [56]:
a2=np.diag(np.arange(0,10))
a2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [57]:
a2.shape

(10, 10)

### 5. Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.


In [69]:
a1=np.arange(1,17).reshape(4,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
a1[:,[0,-1]]=a1[:,[-1,0]]
a1[:,[1,2]]=a1[:,[2,1]]
a1

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

### 6.  Write a program to reverse an array (the first element becomes the last).Given array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [84]:
a1=np.arange(12,28)[::-1]
a1

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

### 7.  Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [86]:
a1=np.arange(1,101).reshape(10,10)
a1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [92]:
a1[(a1>=30) & (a1<80) & (a1%5==0)]

array([30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

### 8. Write a program to create a 2D array with 1 on the border and 0 inside.


In [106]:
a1=np.ones((4,4),dtype=int)
a1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [108]:
a1[1:3,1:3]=0
a1

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

### 9. Write a program to create a checkerboard pattern .Don't use default array function

In [136]:
a1=np.ones((8,8),dtype=int)
a1[[0,0,0,0],[0,2,4,6]]=0
a1[[1,1,1,1],[1,3,5,7]]=0
a1[[2,2,2,2],[0,2,4,6]]=0
a1[[3,3,3,3],[1,3,5,7]]=0
a1[[4,4,4,4],[0,2,4,6]]=0
a1[[5,5,5,5],[1,3,5,7]]=0
a1[[6,6,6,6],[0,2,4,6]]=0
a1[[7,7,7,7],[1,3,5,7]]=0
a1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 10. Write a program to find common values between two arrays.

In [129]:
x=np.arange(1,16).reshape(5,3)
y=np.arange(12,28).reshape(4,4)
n=[]
for i in x.flatten():
    for j in y.flatten():
        if i==j:
            n.append(i)
print(n)

[12, 13, 14, 15]


### 11. Write a program to create an array 2d array and then reshape into 1d array


In [115]:
a1=np.arange(1,17).reshape(4,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [116]:
a1.reshape(16,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### 12.  Write a user defined function for creating a 1 or 2d array from scratch without using array functions
