In [2]:
import numpy as np

In [2]:
data=np.genfromtxt(r"C:\Users\prave\Downloads\tipsf.csv",delimiter=",",skip_header=1)

In [3]:
datac=data.copy()

## 1.Solve the below problem by using only numpy on tip data set 


In [4]:
datac

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

### 1. What is the total bill value?

In [5]:
np.sum(datac[:,1])

4827.77

### 2. What is the total tip value?


In [7]:
np.sum(datac[:,2])

731.5799999999999

### 3. Count how many sun,sat,thu,fri are there.

In [8]:
x1=np.unique(datac[:,5],return_counts=True)
a,s=x1
y=0
for i in a:
    if(i==0):
        print("sun = ",s[y])
        y+=1
    elif(i==1):
        print("sat = ",s[y])
        y+=1
    elif(i==2):
        print("thu = ",s[y])
        y+=1
    else:
        print("fri = ",s[y])
        y+=1

sun =  87
sat =  76
thu =  62
fri =  19


### 4. How many smokers are there?

In [9]:
np.sum(datac[:,4])

93.0

### 5. What is the avg tip given by females and males?


In [14]:
x1=np.sum(datac[:,2].take(np.where(datac[:,3]==0)))
x2=np.sum(datac[:,2].take(np.where(datac[:,3]==1)))
y=np.unique(datac[:,3],return_counts=True)
q,z=y
print(x1/z[0],"avg tip by female")
print(x1/z[1],"avg tip by male")

2.8334482758620685 avg tip by female
1.5701273885350315 avg tip by male


### 6. How much amount has been spent by male and female?


In [16]:
y1=np.sum(datac[:,1].take(np.where(datac[:,3]==0)))
y2=np.sum(datac[:,1].take(np.where(datac[:,3]==1)))
print(y1,"= amount spent by females")
print(y2,"= amount spent by males") 

1570.9499999999996 = amount spent by females
3256.8199999999997 = amount spent by males


### 7. What is the min and max tip?

In [19]:
np.min(datac[:,2])

1.0

In [20]:
np.max(datac[:,2])


10.0

### 8. How many male and female are going for dinner and lunch?

In [26]:
x1=np.unique(datac[:,3].take(np.where((datac[:,6]==1))),return_counts=True)      
a,b=x1
x2=np.unique(datac[:,3].take(np.where((datac[:,6]==0))),return_counts=True)      
c,d=x2
for i in a:
    if(i==0):
        print("total female going for lunch",b[0])
        print("total female going for dinner",d[0])
    else:
         print("total male going for lunch",b[1])
         print("total female going for dinner",d[1])


total female going for lunch 35
total female going for dinner 52
total male going for lunch 33
total female going for dinner 124


### 9. Find out the avg size

In [28]:
np.mean(datac[:,7])

2.569672131147541

### 10. How many female and male smokers are there?


In [38]:
x1=np.unique(datac[:,3].take(np.where(datac[:,4]==1)),return_counts=True)
a,b=x1
for i in a:
    if (i==0):
        print("Female smokers : ",b[0])
    else:
        print("Male smokers : ",b[1])


Female smokers :  33
Male smokers :  60


## 2.Solve the below problem by using only numpy functions on the  below given data set

In [4]:
t=np.genfromtxt(r"C:\Users\prave\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [14]:
train=t.copy()

In [15]:
train

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

### 1.What is max and min length?

In [18]:
np.max(train[:,0])

7.58349125

In [19]:
np.min(train[:,0])

0.0

### 2. Difference between max and min length


In [20]:
np.max(train[:,0])-np.min(train[:,0])

7.58349125

### 3.Find column wise average

In [22]:
np.mean(train,axis=0)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

### 4.Find out all the age whose height is greater than 0.4

In [25]:
x1=train[:,7].take(np.where(train[:,2]>0.4))

In [26]:
x1

array([[11., 14., 13., ..., 11., 11., 11.]])

### 5. Avg height,weight whose age is 10

In [34]:
x1=np.array(train[:,2].take(np.where(train[:,7]==10)))
print("avg height whose age is 10 = ",np.mean(x1))
x2=np.array(train[:,3].take(np.where(train[:,7]==10)))
print("avg weight whose age is 10 = ",np.mean(x2))

avg height whose age is 10 =  0.3833672856539947
avg weight whose age is 10 =  28.243308450511314


### 6. What is total shell weight?

In [37]:
np.sum(train[:,6])

1326845.8295214002

### 7. How many people belongs to each and every unique age

In [46]:
np.unique(train[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

### 8. Difference b/w shuckled and viscera weight

In [47]:
x1=np.sum(train[:,4])
x2=np.sum(train[:,5])
print("Difference b/w shuckled and viscera weight = ",x1-x2)

Difference b/w shuckled and viscera weight =  999237.8582600503


### 9. Avg height of person whose age is greater than 14 and less than 19

In [52]:
x1=np.array(train[:,2].take(np.where((train[:,7]>14) & (train[:,7]<19))))
np.mean(x1)


0.4190701892744479

### 10 . Avg weight if we include all weights

In [54]:
x1=np.sum(train[:,3:7])

In [56]:
train.shape

(200000, 8)

In [57]:
s=list(train.shape)

In [58]:
s[0]

200000

In [63]:
print("Avg weight if we include all weights = ",x1/s[0])

Avg weight if we include all weights =  44.740216665387145
